TURTLE_NECK_ANGLE_THRESHOLD = 18.0
TORSO_ANGLE_THRESHOLD = 28.0
SHOULDER_ANGLE_THRESHOLD = 8.0
PELVIS_ANGLE_THRESHOLD = 7.0
HEAD_TILT_ANGLE_THRESHOLD = 5.0
SPINE_LEAN_ANGLE_THRESHOLD = 8.0

WEIGHT_NECK = 25.0
WEIGHT_TRUNK = 30.0
WEIGHT_SHOULDER = 30.0
WEIGHT_PELVIS = 15.0
WEIGHT_LEG_CROSS = 1.0
